"""user somment table

Revision ID: 31d558c9606d
Revises: 
Create Date: 2021-12-04 17:35:40.054089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d558c9606d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_comment_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_comment_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_comment_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_comment_username'))
        batch_op.drop_index(batch_op.f('ix_user_comment_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_comment_email'))

    op.drop_table('user_comment')
    # ### end Alembic commands ###
