"""comment table relalationship

Revision ID: 768591e6b932
Revises: b8a2121948ac
Create Date: 2021-04-21 03:53:12.308080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768591e6b932'
down_revision = 'b8a2121948ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'admin_id')
    # ### end Alembic commands ###
