"""article 2 table

Revision ID: b8a2121948ac
Revises: de878714b18b
Create Date: 2021-04-19 03:38:03.600502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a2121948ac'
down_revision = 'de878714b18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('allowed_comment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article2_email'), 'article2', ['email'], unique=False)
    op.create_index(op.f('ix_article2_timestamp'), 'article2', ['timestamp'], unique=False)
    op.create_index(op.f('ix_article2_username'), 'article2', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article2_username'), table_name='article2')
    op.drop_index(op.f('ix_article2_timestamp'), table_name='article2')
    op.drop_index(op.f('ix_article2_email'), table_name='article2')
    op.drop_table('article2')
    # ### end Alembic commands ###
