"""fix how to add admin_id field in comment table

Revision ID: beb1ca0098c2
Revises: edf3491d4931
Create Date: 2021-04-21 04:11:56.307075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb1ca0098c2'
down_revision = 'edf3491d4931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'admin', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'admin_id')
    # ### end Alembic commands ###
